
CREATE TABLE POST(
                     ID NUMERIC,
                     CONSTRAINT POST_PK PRIMARY KEY(ID),
                     MESSAGE VARCHAR(200),
                     DATE_POSTED TIMESTAMP,
                     LOCATION VARCHAR(200),
                     USER_POSTED_ID NUMERIC,
                     CONSTRAINT USER_POSTED_FK FOREIGN KEY(USER_POSTED_ID) REFERENCES USERS(ID),
                     USER_PAGE_POSTED_ID NUMERIC,
                     CONSTRAINT USER_PAGE_POSTED_FK FOREIGN KEY(USER_PAGE_POSTED_ID) REFERENCES USERS(ID)
);

CREATE SEQUENCE POST_ID_SEQ
    MINVALUE 1
    INCREMENT BY 1;