CREATE TABLE RELATIONSHIP(
                             USER_FROM_ID INTEGER,
                             CONSTRAINT RELATIONSHIP_USER_FROM_FK FOREIGN KEY(USER_FROM_ID) REFERENCES USERS(ID),
                             USER_TO_ID INTEGER,
                             CONSTRAINT RELATIONSHIP_USER_TO_FK FOREIGN KEY(USER_TO_ID) REFERENCES USERS(ID),
                             STATUS VARCHAR(50) NOT NULL,
                             DATE_MODIFIED TIMESTAMP
);

CREATE SEQUENCE RELATIONSHIP_ID_SEQ
    MINVALUE 1
    INCREMENT BY 1;